image: Visual Studio 2015
configuration:
- Debug
- DebugDLL
- Release
- ReleaseDLL

platform:
- x86
- x64

build:
  project: win32\VS2015\libogg.sln
  parallel: true
  verbosity: minimal

after_build:
- cmd: 7z a ogg.zip win32\VS2015\%PLATFORM%\%CONFIGURATION%\libogg.lib include\ogg\*.h
- cmd: if exist win32\VS2015\%PLATFORM%\%CONFIGURATION%\libogg.dll 7z a ogg.zip win32\VS2015\%PLATFORM%\%CONFIGURATION%\libogg.dll

artifacts:
- path: ogg.zip
